name: DragonCast
author: Peace1333
version: 1.3
website: http://www.bukkit.org
main: Main.Main
commands:
     dc on:
              description: Aktiviert den Automessager
              usage: /<command>
     dc off:
              description: Deaktiviert den Automessager
              usage: /<command>
     dc:
              description: DragonCast Grundbefehl
              usage: /<command>
     dc reload:
              description: Reloadet die Config
              usage: /<command>